SELECT CT_Name ,CT_AgeArea FROM CAMP_TEAM;
SELECT * FROM CA_CHRONIC_DISEASE;
SELECT FA_StartTime, FA_EndTime FROM FACILITY_WORKHOURS WHERE FA_Name="Pisina";
SELECT CE_Name, CE_Age, CE_Role FROM CAMP_EMPLOYEE ORDER BY CE_Age;
SELECT CA_Name, CA_Surname, CA_Age, CA_D_Name, CA_D_Pnum, CA_P_Email, CA_P_Pnum FROM CAMPER WHERE CA_P_Name="Kostas" AND CA_P_Surname="Karapanos" ORDER BY CA_Age;
