CREATE TABLE FACILITY(
    FA_Name VARCHAR(32) NOT NULL,
    FA_Capacity SMALLINT NULL,
    PRIMARY KEY(FA_Name)
);

CREATE TABLE FACILITY_WORKHOURS(
    FA_StartTime TIME(2) NOT NULL,
    FA_EndTime TIME(2) NOT NULL,
    FA_Name VARCHAR(32) NOT NULL,
    PRIMARY KEY(FA_StartTime,FA_EndTime,FA_Name),
    FOREIGN KEY(FA_Name) REFERENCES FACILITY(FA_Name)
);

CREATE TABLE ACTIVITY (
    A_Name VARCHAR(32) NOT NULL,
    A_Location VARCHAR(32) NOT NULL,
    A_StartTime DATETIME(2) NOT NULL,
    A_EndTime DATETIME(2) NOT NULL,
    FA_Name VARCHAR(32) NULL,
    PRIMARY KEY(A_Name),
    FOREIGN KEY(FA_Name) REFERENCES FACILITY(FA_Name)
);

CREATE TABLE CAMP_EMPLOYEE (
    CE_SSN INT UNSIGNED NOT NULL,
    CE_Name VARCHAR(32) NOT NULL,
    CE_Surname VARCHAR(64) NOT NULL,
    CE_Age TINYINT,
    CE_Gender BOOLEAN NOT NULL,
    CE_Role VARCHAR(32) NOT NULL,
    IsMedicalInsured BOOLEAN NOT NULL,
    Profession VARCHAR(15) NULL,
    YearsOfService INT UNSIGNED NOT NULL,
    IsVolunteer BOOLEAN NOT NULL,
    FA_Name VARCHAR(32) NULL,
    PRIMARY KEY(CE_SSN),
    FOREIGN KEY(FA_Name) REFERENCES FACILITY(FA_Name)
);

CREATE TABLE RESPONSIBLE(
    CE_SSN INT UNSIGNED NOT NULL,
    A_Name VARCHAR(32) NOT NULL,
    R_Hours INT UNSIGNED NOT NULL,
    PRIMARY KEY(CE_SSN,A_Name),
    FOREIGN KEY (CE_SSN) REFERENCES CAMP_EMPLOYEE(CE_SSN),
    FOREIGN KEY (A_Name) REFERENCES ACTIVITY(A_Name)
);

CREATE TABLE CAMP_TEAM(
    CT_Name VARCHAR(32) NOT NULL,
    CT_Gender TINYINT NOT NULL,
    CT_AgeArea VARCHAR(15) NOT NULL,
    CT_Maxcnum TINYINT NOT NULL,
    CT_Cnum TINYINT NULL,
    CE_SSN INT UNSIGNED NOT NULL,
    PRIMARY KEY(CT_Name),
    FOREIGN KEY (CE_SSN) REFERENCES CAMP_EMPLOYEE (CE_SSN)
);

CREATE TABLE PARTICIPATE(
    A_Name VARCHAR (32) NOT NULL,
    CT_Name VARCHAR(15) NOT NULL,
    P_HOURS INT UNSIGNED NOT NULL,
    PRIMARY KEY(A_Name,CT_Name),
    FOREIGN KEY(A_Name) REFERENCES ACTIVITY(A_Name),
    FOREIGN KEY(CT_Name) REFERENCES CAMP_TEAM(CT_Name)
);
CREATE TABLE CAMPER (
    CA_SSN int unsigned NOT NULL,   
    CA_Name varchar(32) NOT NULL,   
    CA_Surname varchar(64) NOT NULL,
    CA_Age int unsigned NOT NULL, 
    CA_Pnum bigint NOT NULL,
    CA_Gender BOOL NOT NULL, /* 0: MALE, 1: FEMALE, 2: OTHER */
    CA_KoI tinyint NOT NULL, /* 0: Compatable,1: None*/
    CA_YoR bigint NOT NULL,
    CA_D_Name varchar(32) NOT NULL, 
    CA_D_Pnum BIGINT NOT NULL,
    CA_P_Name varchar(32) NOT NULL,   
    CA_P_Surname varchar(64) NOT NULL,
    CA_P_Email varchar(64) NOT NULL,
    CA_P_Pnum BIGINT NOT NULL,
    CT_Name varchar(32) NOT NULL,
    FA_Name varchar(32) NOT NULL,
    PRIMARY KEY(CA_SSN),
    FOREIGN KEY(CT_Name) REFERENCES CAMP_TEAM(CT_Name),   
    FOREIGN KEY(FA_Name) REFERENCES FACILITY(FA_Name)
);

CREATE TABLE CA_MEDICINE (
    CA_SSN int unsigned NOT NULL,
    Medicine VARCHAR(16),
    PRIMARY KEY(CA_SSN, Medicine),
    FOREIGN KEY(CA_SSN) REFERENCES CAMPER(CA_SSN)
);

CREATE TABLE CA_CHRONIC_DISEASE (
    CA_SSN int unsigned NOT NULL,
    Chronic_Disease VARCHAR(16),
    PRIMARY KEY(CA_SSN, Chronic_Disease),
    FOREIGN KEY(CA_SSN) REFERENCES CAMPER(CA_SSN)
);

CREATE TABLE CA_INFECTIOUS_DISEASE (
    CA_SSN int unsigned NOT NULL,
    Infectious_Disease VARCHAR(16),
    PRIMARY KEY(CA_SSN, Infectious_Disease),
    FOREIGN KEY(CA_SSN) REFERENCES CAMPER(CA_SSN)
);

CREATE TABLE CA_ALLERGY (
    CA_SSN int unsigned NOT NULL,
    Allergy VARCHAR(16),
    PRIMARY KEY(CA_SSN, Allergy),
    FOREIGN KEY(CA_SSN) REFERENCES CAMPER(CA_SSN)
);

